### PR TITLE
Composer app first iteration

### PR DESCRIPTION
**Pull request by miroslav-lalovic-devtech**
# What's the purpose of this MR?
Develop branch, so you could see and comment on changes I've made to the composer app.

#Impact Analysis
(What will this possibly affect?) - My future

#Where should the tester start?
(Hints tips or tricks regarding how to test this, things to watch out for, etc)

#How should this be manually tested?
Guide provided in README.md

#Any background context you want to provide?
Nothing for now.

#What are the relevant tickets?
(N/A)

#Screenshots (if appropriate)
(N/A)

### CODE REVIEW

**Comment by dejan-babic** [comment]
Ok lets start @miroslav-lalovic-devtech 
There is no point of having the vendor folder as part of the repo. Eliminates the purpose of composer then.
Pretty sure you don't need the composer-setup file.
Do you still use the router.php class?
Fix these first please, and we will continue

**Comment by miroslav-lalovic-devtech** [comment]
Removed vendor folder, composer-setup file and router.php as they are redundant.
Updated README file to explain how to run a composer.

Please continue.

Thanks!

**Comment by dejan-babic** [comment]
Ok, since this was a composer basics task, I won't bother you with moving the twin implementation to the bootstrap file. I just want you to think about it, what would you need to do, to move it from index to bootstrap. You will deal with that problem on one of your next  tasks.
The thing you need to do to wrap it up is
Create template for root path 
PHPDoc everywhere

**Comment by dejan-babic** [comment]
And one more note, I've edited the first comment in this PR, you'll get the picture.

**Pull request merged**
